version: "3"
services:
  db:
    image: postgres:11
    container_name: sample_db
    ports:
      - 54320:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
    data: